Adding documentation
whimc/Portals pull request #16
Opened 2021-12-13 18:03 UTC by EmiCB

- Updated the README
- Added JavaDocs and some inline comments to all files

2021-12-16 14:09 UTC, jackah2 requested changes
A handful of changes but pretty minor ones. Thank you for doing this and catching a lot of my mistakes :)

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +Portals is a Minecraft plugin that allows for the creation of custom portals with user-defined destinations. This plugin uses [Multiverse Portals](https://dev.bukkit.org/projects/multiverse-portals).
We don't use multiverse portals - this plugin was meant to replace it actually.

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +Destinations are independent of portals, so you can have many portals link to a single destination. To create a destination to stand in the place you want it and do:
```suggestion
Destinations are independent of portals, so you can have many portals link to a single destination. To create a destination, stand where you'd like it to be and do:
```

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +```yaml
These can all just be normal code blocks. You wouldn't want to format it as yaml unless the content is actually yaml

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +|`/portal create <portal_name>`                       | Creates a permissionless portal using the selected location.       |
```suggestion
|`/portal create <portal_name>`                       | Creates a permissionless portal using the selected area.       |
```

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +
```suggestion

You shouldn't have to edit this file directly; everything can be done with commands.

```

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +|`/portal permission <permission_suffix>`             | Sets or removes portal permissions.                                |
You should add that the required permission ends up being `whimc-portals.entry.<permission_suffix>`

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +|`/destination purge <'invalid'/'no-portals'/'both'>` | Purges any unused and / or invalid destinations.                   |
Specify that "invalid" means it's in a non-existent world and "no-portals" just means it has no linked portals.

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +|`/portal purge <'invalid'/'no-destination'/'both'>`  | Purges any unused and / or invalid portals.                        |
Same comment as the destination purge command

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +To setup a new portal you'll want to use the `wooden sword` tool to `left` and then `right` click two blocks to select an ``empty`` area. Then do:
```suggestion
To setup a new portal you'll want to do `/portal tool` to get the portal selection tool. Then left click to select your first position and right click to select your second. These two blocks will be the bounding corners of a cuboid like WorldEdit. Then do:
```

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +
```suggestion

Note that _only_ air blocks will be replaced with the filler block.

```

2021-12-16 14:09 UTC, jackah2 commented on README.md
> +## Dependencies
There are no dependencies

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/Destination.java
> +    /** @return The list of destinations. */
```suggestion
    /** @return The list of all destinations. */
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/Destination.java
> +    /* The list of destinations. */
```suggestion
    /* The list of all destinations. */
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/Destination.java
> +    /* Keyword for no destination. */
```suggestion
    /** Keyword for no destination. */
```
I believe one-liner javadocs like these should start with a double asterisk

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/Destination.java
> +    /** The location of the Destination. */
```suggestion
    /** @return The location of the Destination. */
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/Portal.java
> + * The class to sore Portal data.
```suggestion
 * The class to store Portal data.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/Main.java
> +    /**
You don't really need this javadoc

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/Portal.java
> +    /* The map of portal data. */
```suggestion
    /* Map of serialized locations to their respective Portal. Allows for fast lookups. */
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/Portal.java
> +    /* The list of portals. */
```suggestion
    /* The list of all portals. */
```
Same comment for the getPortals doc

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/Portal.java
> +     * Sets the configuration of the portal.
```suggestion
     * Sets a value in the config for this portal.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/commands/destination/DestinationCommand.java
> +     * {@inheritDoc}
Add a note about how this has the sub command handle this

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/commands/portal/PortalDebug.java
> + * The command to toggle debug more. Displays information about the portal the user is entering
```suggestion
 * The command to toggle debug mode for the player. Displays information about the portal the user is entering
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalBlockChangeListener.java
> +     * Cancel the water movement if the portal exists.
```suggestion
     * Cancel water/lava movement inside portals.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalBlockChangeListener.java
> +     * Cancel the block formation if the portal exists.
```suggestion
     * Cancel block formations inside portals.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalBlockChangeListener.java
> +     * Cancel the block formation if the portal exists.
```suggestion
     * Stop entities from forming blocks inside portals.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalBlockChangeListener.java
> +     * Cancel the block ignition if the portal exists.
```suggestion
     * Cancel block ignition inside portals.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalBlockChangeListener.java
> + * Listens for events where the portal blocks change.
```suggestion
 * Listens for events where the blocks inside portals change.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalDamageListener.java
> +     * Cancel the combustion event if it is too close to a portal.
```suggestion
     * Stop entities from lighting on fire inside portals. (For lava-filled portals).
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalDamageListener.java
> +     * Cancel damage caused to entities if it is too close to a portal.
```suggestion
     * Stop entitles from taking lava damage from lava-filled portals.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalEnterListener.java
> +     * Adds the UUID of the passed player to hte list of players with debug mode enabled.
```suggestion
     * Enable debug mode for the given player.
```
You don't want to get too into the specifics of the implementation.

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalEnterListener.java
> +     * Removes the UUID of the passed player to the list of players with debug mode enabled.
```suggestion
     * Disable debug mode for the given player.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalEnterListener.java
> +        if (portal == null) return;
Nice catch thank you

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/PortalEnterListener.java
> +        // get the move event locations and check if it's withing the portal bounds
```suggestion
        // return early if the player didn't move a full block.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/listeners/ToolSelectListener.java
> + * Listens for events where a portal tool is selected.
```suggestion
 * Listens for events where a portal tool is used.
```

2021-12-16 14:09 UTC, jackah2 commented on src/main/java/edu/whimc/portals/utils/Messenger.java
> +     * Sends the sender a message about what argument are is unknown and displays the command's
```suggestion
     * Sends the sender a message about providing an unknown argument and displays the command's
```

2021-12-20 16:44 UTC, EmiCB commented on README.md
> +```yaml
Whoops! Looks like I just copy pasted them and forgot to remove the language specifier lol

2021-12-31 21:28 UTC, jackah2 approved these changes
Looks good! Thank you for doing this!

2022-01-11 20:42 UTC, merged